// 
// Decompiled by Procyon v0.5.36
// 

package ccOptions;

import java.util.prefs.Preferences;

public class Options
{
    public static final int TIMEREF_PARIS = 0;
    public static final int TIMEREF_LOCALES = 1;
    public static final int POSROT_SANS_HEURE_CHAQUE_JOUR = 0;
    public static final int POSROT_SANS_HEURE_PREMIER_JOUR = 1;
    public static final int POSROT_PONCTUEL = 2;
    public static final int POSROT_SUR_LA_DUREE = 3;
    public static final int POSROT_SANS_HEURE_DUREE = 4;
    public static final int POSSOL_SANS_HEURE_SUR_LA_DUREE = 0;
    public static final int POSSOL_SANS_HEURE_CHAQUE_JOUR = 1;
    public static final int WEBCOLOR_CREW = 0;
    public static final int WEBCOLOR_PASTEL = 1;
    public static final int WEBCOLOR_NB = 2;
    public static final int WEBFONT_SANS_SERIF = 0;
    public static final int WEBFONT_SERIF = 1;
    public static final int WEBFONT_MONOSPACED = 2;
    public String urlIPN;
    public String loginIpn;
    public String passIpn;
    public int periodImport;
    public boolean isModeFlash;
    public boolean isRosterTableReal;
    public boolean isRosterTableLocal;
    public boolean isRosterTableRetracted;
    public String loginGoogle;
    public boolean isGoogleAuto;
    public String calendarsRotations;
    public String calendarsTroncons;
    public String calendarsActSol;
    public String calendarsConges;
    public String calendarsRepos;
    public String calendarsAbsences;
    public String calendarsDispersions;
    public String colorRotations;
    public String colorTroncons;
    public String colorActSol;
    public String colorConges;
    public String colorRepos;
    public String colorAbsences;
    public String colorDispersions;
    public String loginNightStop;
    public String passNightStop;
    public boolean isNightStopAuto;
    public String[] timeRefItems;
    public int idxTimeRef;
    public String[] positionRotItems;
    public int idxPositionRot;
    public String[] positionSolItems;
    public int idxPositionSol;
    public boolean expRot;
    public boolean expVol;
    public boolean expActSol;
    public boolean expRepos;
    public boolean expConges;
    public boolean expAbsences;
    public boolean expDispersions;
    public String categRot;
    public String categVol;
    public String categActSol;
    public String categConges;
    public String categRepos;
    public String categAbsences;
    public String categDispersions;
    public String persoRot;
    public String persoVol;
    public String persoActSol;
    public String persoConges;
    public String persoRepos;
    public String persoAbsences;
    public String persoDispersions;
    public boolean geneRot;
    public boolean peqRot;
    public boolean recoRot;
    public boolean payeRot;
    public boolean geneTroncon;
    public boolean peqTroncon;
    public boolean recoTroncon;
    public boolean indemTroncon;
    public boolean prestaTroncon;
    public boolean hotelTroncon;
    public boolean payeTroncon;
    public boolean detailsSol;
    public boolean payeSol;
    public String libelleTroncon;
    public boolean lieuMEP;
    public boolean lieuSAB;
    public boolean lieuReco;
    public boolean webTempsVol;
    public boolean webNumVol;
    public boolean webTempsEscale;
    public boolean webPresta;
    public boolean webTypeAvion;
    public boolean webDureeDecoucher;
    public boolean webHotel;
    public boolean webDecalage;
    public boolean webTempsVolSv;
    public boolean webTempsAbsence;
    public boolean webRpc;
    public boolean webReeng;
    public int webColor;
    public int webFont;
    public boolean webMoisComplet;
    public boolean isNoticesCEAuto;
    public boolean isNoticesCETotal;
    public String repNoticesCE;
    public String libelleNoticesCE;
    public String ceLogin;
    public String cePassword;
    public boolean isNoticesAFAuto;
    public boolean isNoticesAFTotal;
    public String repNoticesAF;
    public String libelleNoticesAF;
    public boolean isMajAuto;
    public boolean isSaveAuto;
    public String repSaveAuto;
    public String dbBaremes_pnt;
    public String dbCotis_pnt;
    public String dbBaremes_pnc;
    public String dbCotis_pnc;
    public String dbEscales;
    public String dbTVRef_pnt;
    public String dbTVRef_pnc;
    public String repTXT;
    public String repICS;
    public String repHTML;
    public String repPDF;
    public String repXML;
    public String repPNG;
    public String repCE;
    public String repAF;
    public boolean ep4_progreal;
    public boolean isTooltipMan;
    public boolean isPdfPersoLaurent;
    public boolean isSolTotal;
    
    public Options() {
        this.timeRefItems = new String[] { "Heures de Paris", "Heures locales" };
        this.positionRotItems = new String[] { "sans heure chaque jour engag\u00e9", "sans heure le premier jour engag\u00e9", "ponctuel en d\u00e9but de rotation", "sur la dur\u00e9e de la rotation", "sans heure sur la dur\u00e9e de la rotation" };
        this.positionSolItems = new String[] { "sans heure sur la dur\u00e9e de l'activit\u00e9", "sans heure chaque jour" };
    }
    
    public void initOptions() {
        this.passIpn = "";
        this.periodImport = 0;
        this.isModeFlash = false;
        this.ep4_progreal = false;
        this.isMajAuto = true;
        this.isSaveAuto = false;
        this.repSaveAuto = "";
        this.isSolTotal = false;
        this.isTooltipMan = false;
        this.isPdfPersoLaurent = false;
    }
    
    public void loadPreferences() {
        final Preferences prefs = Preferences.userRoot().node("ChopeCREW/options");
        this.urlIPN = prefs.get("urlIPN", "");
        this.loginIpn = prefs.get("loginIpn", "");
        this.isRosterTableRetracted = prefs.getBoolean("isRosterTableRetracted", false);
        this.isRosterTableReal = prefs.getBoolean("isRosterTableReal", false);
        this.isRosterTableLocal = prefs.getBoolean("isRosterTableLocal", false);
        this.loginGoogle = prefs.get("loginGoogle", "");
        this.isGoogleAuto = prefs.getBoolean("isGoogleAuto", false);
        this.calendarsRotations = prefs.get("calendarsRotations", "");
        this.calendarsTroncons = prefs.get("calendarsTroncons", "");
        this.calendarsActSol = prefs.get("calendarsActSol", "");
        this.calendarsConges = prefs.get("calendarsConges", "");
        this.calendarsRepos = prefs.get("calendarsRepos", "");
        this.calendarsAbsences = prefs.get("calendarsAbsences", "");
        this.calendarsDispersions = prefs.get("calendarsDispersions", "");
        this.colorRotations = prefs.get("colorRotations", "9");
        this.colorTroncons = prefs.get("colorTroncons", "1");
        this.colorActSol = prefs.get("colorActSol", "4");
        this.colorConges = prefs.get("colorConges", "10");
        this.colorRepos = prefs.get("colorRepos", "10");
        this.colorAbsences = prefs.get("colorAbsences", "5");
        this.colorDispersions = prefs.get("colorDispersions", "8");
        this.loginNightStop = prefs.get("loginNightStop", "");
        this.passNightStop = prefs.get("passNightStop", "");
        this.isNightStopAuto = prefs.getBoolean("isNightStopAuto", false);
        this.idxTimeRef = prefs.getInt("idxTimeRef", 0);
        this.idxPositionRot = prefs.getInt("idxPositionRot", 0);
        this.idxPositionSol = prefs.getInt("idxPositionSol", 0);
        this.expRot = prefs.getBoolean("expRot", true);
        this.expVol = prefs.getBoolean("expVol", true);
        this.expActSol = prefs.getBoolean("expActSol", true);
        this.expRepos = prefs.getBoolean("expRepos", true);
        this.expConges = prefs.getBoolean("expConges", true);
        this.expAbsences = prefs.getBoolean("expAbsences", true);
        this.expDispersions = prefs.getBoolean("expDispersions", true);
        this.categRot = prefs.get("categRot", "");
        this.categVol = prefs.get("categVol", "");
        this.categActSol = prefs.get("categActSol", "");
        this.categConges = prefs.get("categConges", "");
        this.categRepos = prefs.get("categRepos", "");
        this.categAbsences = prefs.get("categAbsences", "");
        this.categDispersions = prefs.get("categDispersions", "");
        this.persoRot = prefs.get("persoRot", "");
        this.persoVol = prefs.get("persoVol", "");
        this.persoActSol = prefs.get("persoActSol", "");
        this.persoConges = prefs.get("persoConges", "");
        this.persoRepos = prefs.get("persoRepos", "");
        this.persoAbsences = prefs.get("persoAbsences", "");
        this.persoDispersions = prefs.get("persoDispersions", "");
        this.geneRot = prefs.getBoolean("geneRot", true);
        this.peqRot = prefs.getBoolean("peqRot", true);
        this.recoRot = prefs.getBoolean("recoRot", true);
        this.payeRot = prefs.getBoolean("payeRot", true);
        this.geneTroncon = prefs.getBoolean("geneTroncon", true);
        this.peqTroncon = prefs.getBoolean("peqTroncon", true);
        this.recoTroncon = prefs.getBoolean("recoTroncon", true);
        this.indemTroncon = prefs.getBoolean("indemTroncon", true);
        this.prestaTroncon = prefs.getBoolean("prestaTroncon", true);
        this.hotelTroncon = prefs.getBoolean("hotelTroncon", true);
        this.payeTroncon = prefs.getBoolean("payeTroncon", true);
        this.detailsSol = prefs.getBoolean("detailsSol", true);
        this.payeSol = prefs.getBoolean("payeSol", true);
        this.libelleTroncon = prefs.get("libelleTroncon", "%n | %d - %a | %t");
        this.lieuMEP = prefs.getBoolean("lieuMEP", false);
        this.lieuSAB = prefs.getBoolean("lieuSAB", false);
        this.lieuReco = prefs.getBoolean("lieuReco", false);
        this.webTempsVol = prefs.getBoolean("webTempsVol", true);
        this.webNumVol = prefs.getBoolean("webNumVol", true);
        this.webTempsEscale = prefs.getBoolean("webTempsEscale", true);
        this.webPresta = prefs.getBoolean("webPresta", true);
        this.webTypeAvion = prefs.getBoolean("webTypeAvion", true);
        this.webDureeDecoucher = prefs.getBoolean("webDureeDecoucher", true);
        this.webHotel = prefs.getBoolean("webHotel", true);
        this.webDecalage = prefs.getBoolean("webDecalage", true);
        this.webTempsVolSv = prefs.getBoolean("webTempsVolSv", true);
        this.webTempsAbsence = prefs.getBoolean("webTempsAbsence", true);
        this.webRpc = prefs.getBoolean("webRpc", true);
        this.webReeng = prefs.getBoolean("webReeng", true);
        this.webColor = prefs.getInt("webColor", 1);
        this.webFont = prefs.getInt("webFont", 0);
        this.webMoisComplet = prefs.getBoolean("webMoisComplet", false);
        this.isNoticesCEAuto = prefs.getBoolean("isNoticesCEAuto", false);
        this.isNoticesCETotal = prefs.getBoolean("isNoticesCETotal", false);
        this.repNoticesCE = prefs.get("repNoticesCE", "");
        this.libelleNoticesCE = prefs.get("libelleNoticesCE", "%c-%n_CE");
        this.ceLogin = prefs.get("ceLogin", "");
        this.cePassword = prefs.get("cePassword", "");
        this.isNoticesAFAuto = prefs.getBoolean("isNoticesAFAuto", false);
        this.isNoticesAFTotal = prefs.getBoolean("isNoticesAFTotal", false);
        this.repNoticesAF = prefs.get("repNoticesAF", "");
        this.libelleNoticesAF = prefs.get("libelleNoticesAF", "%c-%n_AF");
        this.isMajAuto = prefs.getBoolean("isMajAuto", false);
        this.isSaveAuto = prefs.getBoolean("isSaveAuto", false);
        this.repSaveAuto = prefs.get("repSaveAuto", "");
        this.dbBaremes_pnt = prefs.get("dbBaremes_pnt", "");
        this.dbBaremes_pnc = prefs.get("dbBaremes_pnc", "");
        this.dbCotis_pnt = prefs.get("dbCotis_pnt", "");
        this.dbCotis_pnc = prefs.get("dbCotis_pnc", "");
        this.dbEscales = prefs.get("dbEscales", "");
        this.dbTVRef_pnt = prefs.get("dbTVRef_pnt", "");
        this.dbTVRef_pnc = prefs.get("dbTVRef_pnc", "");
        this.repTXT = prefs.get("repTXT", "");
        this.repICS = prefs.get("repICS", "");
        this.repHTML = prefs.get("repHTML", "");
        this.repXML = prefs.get("repXML", "");
        this.repPDF = prefs.get("repPDF", "");
        this.repPNG = prefs.get("repPNG", "");
        this.repCE = prefs.get("repCE", "");
        this.repAF = prefs.get("repAF", "");
    }
    
    public void savePreferences() {
        final Preferences prefs = Preferences.userRoot().node("ChopeCREW/options");
        prefs.put("urlIPN", this.urlIPN);
        prefs.put("loginIpn", this.loginIpn);
        prefs.putBoolean("isRosterTableRetracted", this.isRosterTableRetracted);
        prefs.putBoolean("isRosterTableReal", this.isRosterTableReal);
        prefs.putBoolean("isRosterTableLocal", this.isRosterTableLocal);
        prefs.put("loginGoogle", this.loginGoogle);
        prefs.putBoolean("isGoogleAuto", this.isGoogleAuto);
        prefs.put("calendarsRotations", this.calendarsRotations);
        prefs.put("calendarsTroncons", this.calendarsTroncons);
        prefs.put("calendarsActSol", this.calendarsActSol);
        prefs.put("calendarsConges", this.calendarsConges);
        prefs.put("calendarsRepos", this.calendarsRepos);
        prefs.put("calendarsAbsences", this.calendarsAbsences);
        prefs.put("calendarsDispersions", this.calendarsDispersions);
        prefs.put("colorRotations", this.colorRotations);
        prefs.put("colorTroncons", this.colorTroncons);
        prefs.put("colorActSol", this.colorActSol);
        prefs.put("colorConges", this.colorConges);
        prefs.put("colorRepos", this.colorRepos);
        prefs.put("colorAbsences", this.colorAbsences);
        prefs.put("colorDispersions", this.colorDispersions);
        prefs.put("loginNightStop", this.loginNightStop);
        prefs.put("passNightStop", this.passNightStop);
        prefs.putBoolean("isNightStopAuto", this.isNightStopAuto);
        prefs.putInt("idxTimeRef", this.idxTimeRef);
        prefs.putInt("idxPositionRot", this.idxPositionRot);
        prefs.putInt("idxPositionSol", this.idxPositionSol);
        prefs.putBoolean("expRot", this.expRot);
        prefs.putBoolean("expVol", this.expVol);
        prefs.putBoolean("expActSol", this.expActSol);
        prefs.putBoolean("expRepos", this.expRepos);
        prefs.putBoolean("expConges", this.expConges);
        prefs.putBoolean("expAbsences", this.expAbsences);
        prefs.putBoolean("expDispersions", this.expDispersions);
        prefs.put("categRot", this.categRot);
        prefs.put("categVol", this.categVol);
        prefs.put("categActSol", this.categActSol);
        prefs.put("categConges", this.categConges);
        prefs.put("categRepos", this.categRepos);
        prefs.put("categAbsences", this.categAbsences);
        prefs.put("categDispersions", this.categDispersions);
        prefs.put("persoRot", this.persoRot);
        prefs.put("persoVol", this.persoVol);
        prefs.put("persoActSol", this.persoActSol);
        prefs.put("persoConges", this.persoConges);
        prefs.put("persoRepos", this.persoRepos);
        prefs.put("persoAbsences", this.persoAbsences);
        prefs.put("persoDispersions", this.persoDispersions);
        prefs.putBoolean("geneRot", this.geneRot);
        prefs.putBoolean("peqRot", this.peqRot);
        prefs.putBoolean("recoRot", this.recoRot);
        prefs.putBoolean("payeRot", this.payeRot);
        prefs.putBoolean("geneTroncon", this.geneTroncon);
        prefs.putBoolean("peqTroncon", this.peqTroncon);
        prefs.putBoolean("recoTroncon", this.recoTroncon);
        prefs.putBoolean("indemTroncon", this.indemTroncon);
        prefs.putBoolean("prestaTroncon", this.prestaTroncon);
        prefs.putBoolean("hotelTroncon", this.hotelTroncon);
        prefs.putBoolean("payeTroncon", this.payeTroncon);
        prefs.putBoolean("detailsSol", this.detailsSol);
        prefs.putBoolean("payeSol", this.payeSol);
        prefs.put("libelleTroncon", this.libelleTroncon);
        prefs.putBoolean("lieuMEP", this.lieuMEP);
        prefs.putBoolean("lieuSAB", this.lieuSAB);
        prefs.putBoolean("lieuReco", this.lieuReco);
        prefs.putBoolean("webTempsVol", this.webTempsVol);
        prefs.putBoolean("webNumVol", this.webNumVol);
        prefs.putBoolean("webTempsEscale", this.webTempsEscale);
        prefs.putBoolean("webPresta", this.webPresta);
        prefs.putBoolean("webTypeAvion", this.webTypeAvion);
        prefs.putBoolean("webDureeDecoucher", this.webDureeDecoucher);
        prefs.putBoolean("webHotel", this.webHotel);
        prefs.putBoolean("webDecalage", this.webDecalage);
        prefs.putBoolean("webTempsVolSv", this.webTempsVolSv);
        prefs.putBoolean("webTempsAbsence", this.webTempsAbsence);
        prefs.putBoolean("webRpc", this.webRpc);
        prefs.putBoolean("webReeng", this.webReeng);
        prefs.putInt("webColor", this.webColor);
        prefs.putInt("webFont", this.webFont);
        prefs.putBoolean("webMoisComplet", this.webMoisComplet);
        prefs.putBoolean("isNoticesCEAuto", this.isNoticesCEAuto);
        prefs.putBoolean("isNoticesCETotal", this.isNoticesCETotal);
        prefs.put("repNoticesCE", this.repNoticesCE);
        prefs.put("libelleNoticesCE", this.libelleNoticesCE);
        prefs.put("ceLogin", this.ceLogin);
        prefs.put("cePassword", this.cePassword);
        prefs.putBoolean("isNoticesAFAuto", this.isNoticesAFAuto);
        prefs.putBoolean("isNoticesAFTotal", this.isNoticesAFTotal);
        prefs.put("repNoticesAF", this.repNoticesAF);
        prefs.put("libelleNoticesAF", this.libelleNoticesAF);
        prefs.putBoolean("isMajAuto", this.isMajAuto);
        prefs.putBoolean("isSaveAuto", this.isSaveAuto);
        prefs.put("repSaveAuto", this.repSaveAuto);
        prefs.put("dbBaremes_pnt", this.dbBaremes_pnt);
        prefs.put("dbBaremes_pnc", this.dbBaremes_pnc);
        prefs.put("dbCotis_pnt", this.dbCotis_pnt);
        prefs.put("dbCotis_pnc", this.dbCotis_pnc);
        prefs.put("dbEscales", this.dbEscales);
        prefs.put("dbTVRef_pnt", this.dbTVRef_pnt);
        prefs.put("dbTVRef_pnc", this.dbTVRef_pnc);
        prefs.put("repTXT", this.repTXT);
        prefs.put("repICS", this.repICS);
        prefs.put("repHTML", this.repHTML);
        prefs.put("repXML", this.repXML);
        prefs.put("repPDF", this.repPDF);
        prefs.put("repPNG", this.repPNG);
        prefs.put("repCE", this.repCE);
        prefs.put("repAF", this.repAF);
    }
}
